syntax = "proto3";

option csharp_namespace = "tradecube.api";

package tradecube;

service Dealers {
  rpc FindDealer(FindRequest) returns (Dealer);
  rpc CalculatePrice(CalculatePriceRequest) returns (CalculatePriceResponse);
}

message FindRequest {
  string labcode = 1;
  string dealernumber = 2;
}

message Dealer {
  string labcode = 1;
  string dealernumber = 2;
  string dealerid = 3;
  string groupid = 4;
  string makeid = 5;
}

message Price {
  string articlenumber = 1;
  double price = 2;
}

message CalculatePriceRequest {
	Dealer dealer = 1;
	string sourcereference = 2;
}

message CalculatePriceResponse {
  repeated Price dealerprices = 1;
  repeated Price consumerprices = 2;

  double totaldealerprice = 3;
  double totalconsumerprice = 4;
}