// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dealer.proto

package dealer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labcode       string                 `protobuf:"bytes,1,opt,name=labcode,proto3" json:"labcode,omitempty"`
	Dealernumber  string                 `protobuf:"bytes,2,opt,name=dealernumber,proto3" json:"dealernumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_dealer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dealer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_dealer_proto_rawDescGZIP(), []int{0}
}

func (x *FindRequest) GetLabcode() string {
	if x != nil {
		return x.Labcode
	}
	return ""
}

func (x *FindRequest) GetDealernumber() string {
	if x != nil {
		return x.Dealernumber
	}
	return ""
}

type Dealer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labcode       string                 `protobuf:"bytes,1,opt,name=labcode,proto3" json:"labcode,omitempty"`
	Dealernumber  string                 `protobuf:"bytes,2,opt,name=dealernumber,proto3" json:"dealernumber,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dealer) Reset() {
	*x = Dealer{}
	mi := &file_dealer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dealer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dealer) ProtoMessage() {}

func (x *Dealer) ProtoReflect() protoreflect.Message {
	mi := &file_dealer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dealer.ProtoReflect.Descriptor instead.
func (*Dealer) Descriptor() ([]byte, []int) {
	return file_dealer_proto_rawDescGZIP(), []int{1}
}

func (x *Dealer) GetLabcode() string {
	if x != nil {
		return x.Labcode
	}
	return ""
}

func (x *Dealer) GetDealernumber() string {
	if x != nil {
		return x.Dealernumber
	}
	return ""
}

func (x *Dealer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_dealer_proto protoreflect.FileDescriptor

const file_dealer_proto_rawDesc = "" +
	"\n" +
	"\fdealer.proto\x12\x06dealer\"K\n" +
	"\vFindRequest\x12\x18\n" +
	"\alabcode\x18\x01 \x01(\tR\alabcode\x12\"\n" +
	"\fdealernumber\x18\x02 \x01(\tR\fdealernumber\"`\n" +
	"\x06Dealer\x12\x18\n" +
	"\alabcode\x18\x01 \x01(\tR\alabcode\x12\"\n" +
	"\fdealernumber\x18\x02 \x01(\tR\fdealernumber\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress2;\n" +
	"\aDealers\x120\n" +
	"\tFindBasic\x12\x13.dealer.FindRequest\x1a\x0e.dealer.DealerB\x18Z\t./;dealer\xaa\x02\n" +
	"dealer.apib\x06proto3"

var (
	file_dealer_proto_rawDescOnce sync.Once
	file_dealer_proto_rawDescData []byte
)

func file_dealer_proto_rawDescGZIP() []byte {
	file_dealer_proto_rawDescOnce.Do(func() {
		file_dealer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dealer_proto_rawDesc), len(file_dealer_proto_rawDesc)))
	})
	return file_dealer_proto_rawDescData
}

var file_dealer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dealer_proto_goTypes = []any{
	(*FindRequest)(nil), // 0: dealer.FindRequest
	(*Dealer)(nil),      // 1: dealer.Dealer
}
var file_dealer_proto_depIdxs = []int32{
	0, // 0: dealer.Dealers.FindBasic:input_type -> dealer.FindRequest
	1, // 1: dealer.Dealers.FindBasic:output_type -> dealer.Dealer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dealer_proto_init() }
func file_dealer_proto_init() {
	if File_dealer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dealer_proto_rawDesc), len(file_dealer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dealer_proto_goTypes,
		DependencyIndexes: file_dealer_proto_depIdxs,
		MessageInfos:      file_dealer_proto_msgTypes,
	}.Build()
	File_dealer_proto = out.File
	file_dealer_proto_goTypes = nil
	file_dealer_proto_depIdxs = nil
}
