// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: dealer.proto

package dealer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dealers_FindBasic_FullMethodName = "/dealer.Dealers/FindBasic"
)

// DealersClient is the client API for Dealers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DealersClient interface {
	FindBasic(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Dealer, error)
}

type dealersClient struct {
	cc grpc.ClientConnInterface
}

func NewDealersClient(cc grpc.ClientConnInterface) DealersClient {
	return &dealersClient{cc}
}

func (c *dealersClient) FindBasic(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Dealer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dealer)
	err := c.cc.Invoke(ctx, Dealers_FindBasic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DealersServer is the server API for Dealers service.
// All implementations must embed UnimplementedDealersServer
// for forward compatibility.
type DealersServer interface {
	FindBasic(context.Context, *FindRequest) (*Dealer, error)
	mustEmbedUnimplementedDealersServer()
}

// UnimplementedDealersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDealersServer struct{}

func (UnimplementedDealersServer) FindBasic(context.Context, *FindRequest) (*Dealer, error) {
	return nil, status.Error(codes.Unimplemented, "method FindBasic not implemented")
}
func (UnimplementedDealersServer) mustEmbedUnimplementedDealersServer() {}
func (UnimplementedDealersServer) testEmbeddedByValue()                 {}

// UnsafeDealersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DealersServer will
// result in compilation errors.
type UnsafeDealersServer interface {
	mustEmbedUnimplementedDealersServer()
}

func RegisterDealersServer(s grpc.ServiceRegistrar, srv DealersServer) {
	// If the following call panics, it indicates UnimplementedDealersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dealers_ServiceDesc, srv)
}

func _Dealers_FindBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealersServer).FindBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dealers_FindBasic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealersServer).FindBasic(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dealers_ServiceDesc is the grpc.ServiceDesc for Dealers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dealers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dealer.Dealers",
	HandlerType: (*DealersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBasic",
			Handler:    _Dealers_FindBasic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dealer.proto",
}
